version: '3.4'

services:
  node-dev:
    image: node-dev
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../:/workspace
    working_dir: /workspace
    #command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    #command: tail -f /dev/null  #npm run dev
    networks:
      - node-network
      
  mongodb:
    image: mongo:4.2.1-bionic
    environment:
      - MONGO_INIT_DATABASE=boil-test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=acb1234
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge